version: "3"
services:
  server:
    build:
      dockerfile: server.dockerfile
      context: .
    restart: always
  client:
    build:
      dockerfile: client.dockerfile
      context: .
    depends_on:
      - server
    environment:
      - SERVER_ADDR=server:3000
